### ISSUE TITLE
compilation issues on non-linux platforms

### ISSUE THREAD

**Issue by mdrocco** [pnnl/gmt#7]

**Comment by mdrocco** [comment]
The main issue is with `*context` primitives from `ucontext.h` system library (e.g., on mac they are not defined at all). Should we just give up supporting non-linux systems?

**Comment by mminutoli** [comment]
Well, I doesn't make sense to spend time re-writing the context switch and It's too much work to implement the bare minimum internally.  It might be the only option we have right now.

**Comment by Antonyt80** [comment]
Maurizio, Marco,
It does not make sense to support different OSes than Linux for gmt right now.

Do you know of any cluster that uses Mac OS ? :)

IBM also basically killed CNK with blue gene and the cray PE environment is still Linux based ...

Thanks,
Antonino

Antonino Tumeo, Phd
E-mail: ascgroup@me.com<mailto:ascgroup@me.com>

Il giorno 24 mag 2018, alle ore 14:34, Maurizio Drocco <notifications@github.com<mailto:notifications@github.com>> ha scritto:


The main issue is with *context primitives from ucontext.h system library (e.g., on mac they are not defined at all). Should we just give up supporting non-linux systems?

**Comment by mdrocco** [comment]
Ok, anyway I will create a PR for the minimal changes I have made, since they are minor improvements also on linux platforms (e.g., standard syntax for attributes).

**Comment by mminutoli** [comment]
@Antonyt80 the support was meant for debugging purpose on our machine/laptops.  None of us thinks that we need to support clusters of iphones.  Even though, I have to admit it would be cool.

**Comment by Antonyt80** [comment]
What is wrong with a VM with Ubuntu ? :)

Good for the cleanups/improvements, Maurizio!

Antonino Tumeo, Phd
E-mail: ascgroup@me.com<mailto:ascgroup@me.com>

Il giorno 24 mag 2018, alle ore 14:55, Marco Minutoli <notifications@github.com<mailto:notifications@github.com>> ha scritto:


@Antonyt80<https://github.com/Antonyt80> the support was meant for debug purpose on our machine/laptops. None of us thinks that we need to support clusters of iphones. Even though, I have to admit it would be cool.
